drop database expenseTracker_DB;
drop user expenseTracker;
create user expenseTracker with password 'password';
create user expenseTracker_DB with template=template0 owner=expenseTracker;
\connect expenseTracker_DB;
alter default privileges grant all on tables to expenseTracker;
alter default privileges grant all on sequences to expenseTracker;

-- Create table
create table et_users(
user_id integer primary key not null,
first_name varchar(30) not null,
last_name varchar(30) not null,
email varchar(30) not null,
password text not null);

-- Create table
create table ET_CATEGORIES
(
  category_id INTEGER not null,
  user_id     INTEGER not null,
  title       VARCHAR2(28) not null,
  description VARCHAR2(50) not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table ET_CATEGORIES
  add primary key (CATEGORY_ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ET_CATEGORIES
  add constraint CAT_USERS_FK foreign key (USER_ID)
  references ET_USERS (USER_ID);

-- Create table
create table ET_TRANSACTIONS
(
  transaction_id number GENERATED by default on null as identity,
  category_id    INTEGER not null,
  user_id        INTEGER not null,
  amount         NUMBER(10,2) not null,
  note           VARCHAR2(50) not null,
  transaction_date timestamp not null
);
alter table ET_TRANSACTIONS
  add constraint PK_TRANSACTION_ID primary key (TRANSACTION_ID);
alter table ET_TRANSACTIONS
  add constraint TRANS_CAT_FK foreign key (CATEGORY_ID)
  references ET_CATEGORIES (CATEGORY_ID);
alter table ET_TRANSACTIONS
  add constraint TRANS_USER_FK foreign key (USER_ID)
  references ET_USERS (USER_ID);

-- Create table
CREATE table ET_PAYMENT(
PAYMENT_ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
TRANSACTION_ID INTEGER NOT NULL,
MERCHANT_ID VARCHAR(50) NOT NULL,
DATE_TIME VARCHAR(50) NOT NULL
);
alter table ET_PAYMENT add constraint PAY_TRANS_FK
foreign key (TRANSACTION_ID) references ET_TRANSACTIONS(TRANSACTION_ID);

alter table ET_PAYMENT add constraint PK_PAYMENT_ID primary key (PAYMENT_ID);

alter table ET_PAYMENT add ORDER_ID VARCHAR(50) NOT NULL;
alter table ET_PAYMENT add PAYMENT_REF_ID VARCHAR(50) NOT NULL;
alter table ET_PAYMENT MODIFY PAYMENT_REF_ID VARCHAR(100) NOT NULL;